import type { UploadOptions } from 'imagekit-javascript/src/interfaces';

export const BYTES_IN_MB = 1000000;

export const ERRORS = {
	NO_FILE_IN_ENTRY: 'NO_FILE_IN_ENTRY',
	FILE_IS_TOO_BIG: 'FILE_IS_TOO_BIG',
	COUDNT_CONVERT_TO_ARRAYBUFFER: 'COUDNT_CONVERT_TO_ARRAYBUFFER',
	UNSUPPORTED_IMAGE_TYPE: 'UNSUPPORTED_IMAGE_TYPE',
	COULDNT_FIND_ANY_FULL_IMAGE_PROVIDER_CREDENTIALS:
		'COULDNT_FIND_ANY_FULL_IMAGE_PROVIDER_CREDENTIALS',
	COULDNT_CONVERT_TO_BASE64: 'COULDNT_CONVERT_TO_BASE64',
	COULDNT_GET_PIXELS_FOR_COLOR_PROBE: 'COULDNT_GET_PIXELS_FOR_COLOR_PROBE',
	MISSING_CREDENTIALS_ENDPOINT: 'MISSING_CREDENTIALS_ENDPOINT',
	COULDNT_GET_CLIENT_UPLOAD_CREDENTIALS: 'COULDNT_GET_CLIENT_UPLOAD_CREDENTIALS',
	VALIDATE_FILE_FIRST: 'VALIDATE_FILE_FIRST',
	SET_UPLOADER_FROM_USER_FIRST: 'SET_UPLOADER_FROM_USER_FIRST',
	FILE_NOT_SET: 'FILE_WASNT_SET_PROPERLY'
};

export const DEFAULT_IMAGEKIT_UPLOAD_CONFIG: Partial<UploadOptions> = {
	useUniqueFileName: true
};

export const PLAVNA_FOLDER = 'PLAVNA_STORAGE_V0';

export const DEFAULT_BG = 'hsl(0deg, 0%, 50%)';
